<?php
/**
 * TL_ROOT/system/modules/xtmembers_fieldeditor/languages/de/modules.php 
 * 
 * Contao extension: xtmembers_fieldeditor 1.2.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['memberfields']['0'] = "Mitgliederfelder";
$GLOBALS['TL_LANG']['MOD']['memberfields']['1'] = "Dieses Modul erlaubt Ihnen die Erstellung zusätzlicher Mitgliederfelder für TYPOlight Mitglieder.";
 
?>
